#!/usr/bin/env sh

# iterm2
#shift + alt - return : "${HOME}"/.config/yabai/scripts/open_iterm2.sh

# kitty
 shift + alt - return : /Applications/Kitty.app/Contents/MacOS/kitty \
     --single-instance \
     --listen-on unix:/tmp/mykitty \
     -c ${HOME}/.config/kitty/kitty_macos.conf \
     -d ~

alt - return : yabai -m window --swap west # swap with "main" tile by simply swap it west

# Focus window
alt - j : yabai -m window --focus next || yabai -m window --focus first
alt - k : yabai -m window --focus prev || yabai -m window --focus last

# Swap window
shift + alt - j : yabai -m window --swap next
shift + alt - k : yabai -m window --swap prev

# Rotating and axis
alt - r : yabai -m space --rotate 90
alt - y : yabai -m space --mirror y-axis
alt - x : yabai -m space --mirror x-axis

# Resizing
alt - h : expr $(yabai -m query --windows --window | jq .frame.x) \< 20 && yabai -m window --resize right:-60:0 || yabai -m window --resize left:-60:0
alt - l : expr $(yabai -m query --windows --window | jq .frame.x) \< 20 && yabai -m window --resize right:60:0 || yabai -m window --resize left:60:0
alt - i : yabai -m window --resize bottom:0:-60
alt - o : yabai -m window --resize bottom:0:60
alt - e : yabai -m window --toggle split
shift + alt - 0 : yabai -m space --balance

# Move window
alt - return : yabai -m window --warp first
alt + ctrl - return :yabai -m window --warp east # move window out of the "main" tile

## Toggle floating window and center
alt + ctrl - space : yabai -m window --toggle float;\
	yabai -m window --grid 4:4:1:1:2:2 

# Focus space.
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2 
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4 
alt - 5 : yabai -m space --focus 5 
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9
alt - tab : yabai -m window --focus next | yabai -m window --focus prev

# Move window to spaces
shift + alt - 1 : yabai -m window --space 1;
shift + alt - 2 : yabai -m window --space 2;
shift + alt - 3 : yabai -m window --space 3;
shift + alt - 4 : yabai -m window --space 4;
shift + alt - 5 : yabai -m window --space 5;
shift + alt - 6 : yabai -m window --space 6;
shift + alt - 7 : yabai -m window --space 7;
shift + alt - 8 : yabai -m window --space 8;
shift + alt - 9 : yabai -m window --space 9;

# Focus space
alt - left : yabai -m space --focus prev;
alt - right : yabai -m space --focus next;

# Swap space and refresh
alt + ctrl - left : yabai -m space --swap prev;\
  osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "spaces-jsx"'
alt + ctrl - right : yabai -m space --swap next;\
  osascript -e 'tell application id "tracesOf.Uebersicht" to refresh widget id "spaces-jsx"'

# TODO: Integrate keybings for tmux sessions split panes
# Focus window using vim keybinds.
#alt - h [
#* : yabai -m window --focus west
#"kitty" : if [ $(tmux display-message -p '#{pane_at_left}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L";\
#else yabai -m window --focus west || true; fi
#"iTerm2" : if [ $(tmux display-message -p '#{pane_at_left}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L";\
#else yabai -m window --focus west || true; fi
#]
#
#alt - j [ 
#* : yabai -m window --focus south #"kitty" : if [ $(tmux display-message -p '#{pane_at_bottom}') -ne 1 ];\ #then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D";\ #else yabai -m window --focus south || true; fi
#"iTerm2" : if [ $(tmux display-message -p '#{pane_at_bottom}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D";\
#else yabai -m window --focus south || true; fi
#]
#
#alt - k [
#* : yabai -m window --focus north
#"kitty" : if [ $(tmux display-message -p '#{pane_at_top}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U";\
#else yabai -m window --focus north || true; fi
#"iTerm2" : if [ $(tmux display-message -p '#{pane_at_top}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U";\
#else yabai -m window --focus north || true; fi
#]
#
#alt - l [
#* : yabai -m window --focus east
#"kitty" : if [ $(tmux display-message -p '#{pane_at_right}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -L";\
#else yabai -m window --focus east || true; fi
#"iTerm2" : if [ $(tmux display-message -p '#{pane_at_right}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -L";\
#else yabai -m window --focus east || true; fi
#]
##
## Move focused window using vim keybinds.
## Disabled: Using keybinds for tmux.
#shift + alt - h [
#* : yabai -m window --swap west
#"kitty" : if [ $(tmux display-message -p '#{pane_at_left}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L";\
#else yabai -m window --swap west || true; fi
#]
#
#shift + alt - j [
#* : yabai -m window --swap south
#"kitty" : if [ $(tmux display-message -p '#{pane_at_bottom}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D";\
#else yabai -m window --swap south || true; fi
#]
#
#shift + alt - k [
#* : yabai -m window --swap north
#"kitty" : if [ $(tmux display-message -p '#{pane_at_top}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U";\
#else yabai -m window --swap north || true; fi
#]
#
#shift + alt - l [
#* : yabai -m window --swap east
#"kitty" : if [ $(tmux display-message -p '#{pane_at_right}') -ne 1 ];\
#then tmux run "(tmux display-message -p '#{pane_title}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -L";\
#else yabai -m window --swap east || true; fi
#]
