#!/usr/bin/env sh
#
#yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-jsx\"'" label="Refresh on space change"
#yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-jsx\"'" label="Refresh on display focus change"
#yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-jsx\"'" label="Refresh when focused application changes"
#yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-jsx\"'" label="Refresh when front application switched application changes"
#yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-jsx\"'" label="Refresh when an application window is closed"
#yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-jsx\"'" label="Refresh when current window title changes"
#yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"spaces-jsx\"'" label="Refresh spaces-jsx when front application switched application changes"
#
#yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"widgets-jsx\"'" label="Refresh widgets-jsx when current window title changes"
#yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"widgets-jsx\"'" label="Refresh widgets-jsx when front application switched application changes"
#
yabai -m signal --add event=display_changed \
  action="osascript ~/.bin/setwallpaper"
yabai -m signal --add event=application_front_switched \
  action="osascript ~/.bin/setwallpaper"
yabai -m signal --add event=window_destroyed \
  action="osascript ~/.bin/setwallpaper"
yabai -m signal --add event=window_title_changed \
  action="osascript ~/.bin/setwallpaper"
yabai -m signal --add event=space_changed \
  action="osascript ~/.bin/setwallpaper"
