#!/bin/zsh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   on
yabai -m config window_opacity                  on
yabai -m config window_opacity_duration         1
yabai -m config active_window_opacity           1
yabai -m config normal_window_opacity           1
yabai -m config window_border                   off
yabai -m config window_border_width		        4
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    off
yabai -m config mouse_modifier                  ctrl
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize
yabai -m config mouse_drop_action               swap
yabai -m config status_bar                      off

# general space settings
yabai -m config layout                          bsp
yabai -m config external_bar			        all:30:10
#yabai -m config top_padding                     30
#yabai -m config bottom_padding                  5
yabai -m config left_padding                    12
yabai -m config right_padding                   12
yabai -m config window_gap                      12

source $HOME/.config/yabai/rules;
source $HOME/.config/yabai/events;